# Generated by Django 3.2.12 on 2022-04-08 11:20

from django.db import migrations, models
import jewelry_shop.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[jewelry_shop.common.validators.validate_card_number_right_length, jewelry_shop.common.validators.validate_only_numbers])),
                ('expiration_date', models.DateField()),
                ('cvv', models.IntegerField(validators=[jewelry_shop.common.validators.validate_cvv_number_right_length, jewelry_shop.common.validators.validate_only_numbers])),
            ],
        ),
    ]
