# Generated by Django 3.2.12 on 2022-04-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to=''),
        ),
    ]
