# Generated by Django 3.2.12 on 2022-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
