# Generated by Django 3.2.12 on 2022-04-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='products',
        ),
    ]
