# Generated by Django 3.2.12 on 2022-04-13 15:29

from django.db import migrations, models
import django.db.models.deletion
import jewelry_shop.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Pleven', 'Pleven'), ('Sliven', 'Sliven'), ('Dobrich', 'Dobrich'), ('Shumen', 'Shumen')], max_length=7)),
                ('zip_code', models.CharField(max_length=4, validators=[jewelry_shop.common.validators.validate_only_numbers])),
                ('phone_number', models.CharField(max_length=10, validators=[jewelry_shop.common.validators.validate_only_numbers])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.appuser')),
            ],
        ),
    ]
