# Generated by Django 3.2.12 on 2022-04-13 17:10

from django.db import migrations, models
import django.db.models.deletion
import jewelry_shop.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfoView',
            fields=[
                ('card_number', models.CharField(max_length=16, validators=[jewelry_shop.common.validators.validate_only_numbers])),
                ('cvv', models.CharField(max_length=16, validators=[jewelry_shop.common.validators.validate_only_numbers])),
                ('expiration_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.appuser')),
            ],
        ),
    ]
