# Generated by Django 3.2.12 on 2022-04-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cardinfoview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardInfoView',
            new_name='CardInfo',
        ),
    ]
