# Generated by Django 3.2.12 on 2022-04-13 17:26

from django.db import migrations, models
import jewelry_shop.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_cardinfoview_cardinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='cvv',
            field=models.CharField(max_length=3, validators=[jewelry_shop.common.validators.validate_only_numbers]),
        ),
    ]
